### ISSUE TITLE
new netcat module

### ISSUE THREAD

**Issue by roccomuso** [kotarac/gearman_status#1]
I just wanna let you know that there's a better porting of Netcat in node.
Check it out: [netcat](https://github.com/roccomuso/netcat)

**Comment by kotarac** [comment]
Anything in particular that's better about it?

**Comment by roccomuso** [comment]
It implements all netcat's API in a fashion way.
It' a comprehensive porting.

**Comment by kotarac** [comment]
Unless there's a clear gain in maintainability, security, performance or ease of use, I'd argue it's better left as it is.
